# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will build and test a .NET application.
# You can uncomment and adjust the WAP/UWP packaging steps if needed.

name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: TaskHandler.sln
      Test_Project_Path: TaskHandler.Tests/TaskHandler.Tests.csproj
      #Wap_Project_Directory: your-wap-project-directory-name
      #Wap_Project_Path: your-wap-project-path

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install .NET 9 SDK
      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      # Restore dependencies
      - name: Restore the solution
        run: dotnet restore ${{ env.Solution_Name }}

      # Build the solution
      - name: Build solution
        run: dotnet build ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --no-restore

      # Execute all unit tests
      - name: Execute unit tests
        run: dotnet test ${{ env.Test_Project_Path }} --configuration ${{ matrix.configuration }} --no-build